### ISSUE TITLE
feature-request: print name-of-day

### ISSUE THREAD

**Issue by webispy** [chanshik/slack-timezone#1]
현재 출력되는 포맷

    *UTC*: *2019-05-17 04:25:38*
    *Asia/Seoul*
     Local: *2019-05-17 13:25:38+09:00*
     Users: ...
    *America/Los_Angeles*
     Local: *2019-05-16 21:25:38-07:00*
     Users: ...

원하는 포맷

    *UTC*: *2019-05-17 04:25:38*
    *Asia/Seoul*
     Local: *2019-05-17 13:25:38+09:00* Fri
     Users: ...
    *America/Los_Angeles*
     Local: *2019-05-16 21:25:38-07:00* Thu
     Users: ...

**Comment by chanshik** [comment]
Implemented. :+1:
